fix: separate logic for init_release and init_hotfix
The init_release and init_hotfix workflows shared the same logic, even though they shouldn't have

diff --git a/test/scripts/Test_3-init_release-wd b/test/scripts/Test_3-init_release-wd
--- a/test/scripts/Test_3-init_release-wd
+++ b/test/scripts/Test_3-init_release-wd
@@ -16,16 +16,23 @@ teardown() {
   branch="release/v0.0.1"
   cd /target/$1
   git checkout $branch
-  git log --stat
-  if ! git log -1 --pretty=%B | grep -q "#ready"; then
-    echo ERROR: commit message does not contain "#ready"
-    exit 1
+  if ! git log -1 --pretty=%B | sed -n '/Prepare release v0.0.1/,/#ready/p'; then
+      echo ERROR: commit message does not contain "Prepare release v0.0.1" or "#ready"
+      exit 1
   fi
   hash1=$(git merge-base $branch develop)
   hash2=$(git rev-parse develop)
   if [ ! "$hash1" = "$hash2" ]; then
-    echo "ERROR: the branch '$branch' does not originate from 'develop'"
-    exit 1
+      echo "ERROR: the branch '$branch' does not originate from 'develop'"
+      exit 1
+  fi
+  if ! cat CHANGELOG.md | grep -q "\[0.0.1\] \- $(date +%F)"; then
+      echo "ERROR: the changelog file does not contain release version"
+      exit 1
+  fi
+  if ! cat pom.xml | grep -q "<version>0.0.1</version>"; then
+      echo "ERROR: the pom file does not contain release version"
+      exit 1
   fi
 }
 
diff --git a/test/scripts/Test_6-init_hotfix b/test/scripts/Test_6-init_hotfix
--- a/test/scripts/Test_6-init_hotfix
+++ b/test/scripts/Test_6-init_hotfix
@@ -2,9 +2,9 @@
 set -e
 
 event="workflow_dispatch"
-workdir="snapshot"
+workdir="release"
 data="workflow_dispatch-hotfix.json"
-workflow="init_release"
+workflow="init_hotfix"
 
 # --------------------------
 
@@ -13,18 +13,22 @@ setup() {
 }
 
 teardown() {
-  branch="hotfix/v0.0.1"
+  branch="hotfix/v0.0.2"
   cd /target/$1
   git checkout $branch
   git log --stat
-  if ! git log -1 --pretty=%B | grep -q "#ready"; then
-    echo "ERROR: commit message does not contain '#ready'"
+  if ! git log -1 --pretty=%B | grep -q "Prepare for the next patch iteration v0.0.2"; then
+    echo "ERROR: commit message does not contain 'Prepare for the next patch iteration v0.0.2'"
     exit 1
   fi
   hash1=$(git merge-base $branch main)
   hash2=$(git rev-parse main)
   if [ ! "$hash1" = "$hash2" ]; then
     echo "ERROR: the branch '$branch' does not originate from 'main'"
+    exit 1
+  fi
+  if ! cat pom.xml | grep -q "<version>0.0.2-SNAPSHOT</version>"; then
+    echo "ERROR: the pom file does not contain snapshot version"
     exit 1
   fi
 }
